defaults:
  - scope:
      path: "pages"
    values:
      layout: "default"
      sidebar-path: sidebar-L/sidebar-L-default.html
  - scope:
      path: "pages/web-developers"
    values:
      h1: Веб-разработка
      section: Веб-разработка
      brand: web-dev
      embedding-h1: embedding_h1/wed-devel-header.html


exclude:
 - forAI/
 - LICENSE
 - README.md
