defaults:
  - scope:
      path: "pages"
    values:
      layout: "default"
      sidebar-path: sidebar-L/sidebar-L-default.html
  - scope:
      path: "pages/web-developers"
    values:
      h1: Веб-разработка
      section: веб-разработка
      embedding-header: embedding_header/wed-devel-header.html


exclude:
 - forAI/
 - LICENSE
 - README.md
